-- =========================================================
-- MANA MOVEMENT TRAINING v3.2
-- Coach notes + check-in requests
-- =========================================================

create table if not exists public.coach_notes (
  id bigint generated by default as identity primary key,
  coach_id uuid not null references auth.users(id) on delete cascade,
  client_id uuid not null references auth.users(id) on delete cascade,
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (coach_id, client_id)
);

create table if not exists public.checkin_requests (
  id bigint generated by default as identity primary key,
  coach_id uuid not null references auth.users(id) on delete cascade,
  client_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'requested',
  requested_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table public.coach_notes enable row level security;
alter table public.checkin_requests enable row level security;

drop policy if exists "Coach manages own notes" on public.coach_notes;
create policy "Coach manages own notes"
on public.coach_notes
for all
to authenticated
using (
  coach_id = auth.uid()
  and auth.jwt() -> 'app_metadata' ->> 'role' = 'coach'
)
with check (
  coach_id = auth.uid()
  and auth.jwt() -> 'app_metadata' ->> 'role' = 'coach'
);

drop policy if exists "Coach manages own checkin requests" on public.checkin_requests;
create policy "Coach manages own checkin requests"
on public.checkin_requests
for all
to authenticated
using (
  coach_id = auth.uid()
  and auth.jwt() -> 'app_metadata' ->> 'role' = 'coach'
)
with check (
  coach_id = auth.uid()
  and auth.jwt() -> 'app_metadata' ->> 'role' = 'coach'
);

drop policy if exists "Client reads own checkin requests" on public.checkin_requests;
create policy "Client reads own checkin requests"
on public.checkin_requests
for select
to authenticated
using (client_id = auth.uid());

drop policy if exists "Client updates own checkin requests" on public.checkin_requests;
create policy "Client updates own checkin requests"
on public.checkin_requests
for update
to authenticated
using (client_id = auth.uid())
with check (client_id = auth.uid());
