-- =========================================================
-- MANA MOVEMENT TRAINING v3.7
-- Strength exercise weight logging
-- Run ONCE in Supabase SQL Editor
-- =========================================================

create table if not exists public.exercise_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  day_number integer not null check (day_number between 1 and 28),
  exercise_name text not null,
  weight_kg numeric(7,2) not null check (weight_kg >= 0 and weight_kg <= 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, day_number, exercise_name)
);

create index if not exists exercise_logs_user_day_idx
  on public.exercise_logs(user_id, day_number);

alter table public.exercise_logs enable row level security;

drop policy if exists "Client manages own exercise logs" on public.exercise_logs;
create policy "Client manages own exercise logs"
on public.exercise_logs
for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "Coach reads client exercise logs" on public.exercise_logs;
create policy "Coach reads client exercise logs"
on public.exercise_logs
for select
to authenticated
using (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'coach'
);

grant select, insert, update, delete on public.exercise_logs to authenticated;
grant usage, select on sequence public.exercise_logs_id_seq to authenticated;
