-- =========================================================
-- MANA MOVEMENT TRAINING v5.5.0
-- Strength set logging upgrade
-- Run ONCE in Supabase SQL Editor
-- =========================================================

create table if not exists public.exercise_set_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  day_number integer not null check (day_number between 1 and 28),
  exercise_name text not null,
  set_number integer not null check (set_number between 1 and 20),
  reps integer check (reps is null or (reps between 0 and 500)),
  weight_kg numeric(7,2) check (weight_kg is null or (weight_kg >= 0 and weight_kg <= 1000)),
  rpe numeric(3,1) check (rpe is null or (rpe >= 1 and rpe <= 10)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, day_number, exercise_name, set_number)
);

create index if not exists exercise_set_logs_user_day_idx
  on public.exercise_set_logs(user_id, day_number);

create index if not exists exercise_set_logs_user_exercise_idx
  on public.exercise_set_logs(user_id, exercise_name, updated_at desc);

alter table public.exercise_set_logs enable row level security;

drop policy if exists "Client manages own exercise set logs" on public.exercise_set_logs;

create policy "Client manages own exercise set logs"
on public.exercise_set_logs
for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "Coach reads client exercise set logs" on public.exercise_set_logs;

create policy "Coach reads client exercise set logs"
on public.exercise_set_logs
for select
to authenticated
using (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'coach'
);

grant select, insert, update, delete
on public.exercise_set_logs
to authenticated;

grant usage, select
on sequence public.exercise_set_logs_id_seq
to authenticated;
